name: CI

on:
  push:
    branches:
        - main
        - 'development'
        - 'feature/*'
        - 'bugfix/*'
        - 'hotfix/*'
        - 'releases/*'
        - 'v*.*.*'
  pull_request:
    branches:
        - main
        - 'development'
        - 'feature/*'
        - 'bugfix/*'
        - 'hotfix/*'
        - 'releases/*'
        - 'v*.*.*'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests
      run: composer test

    - name: Run static analysis
      run: composer psalm

    - name: Check code style
      run: composer cs-check

    - name: Upload coverage
      if: matrix.php-version == '8.2'
      uses: codecov/codecov-action@v3
